# Generated by Django 6.0.7 on 2026-08-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(default='A', help_text='Which parallel section of their program+semester cohort this student belongs to.', max_length=10),
        ),
    ]
