# Generated by Django 6.0.7 on 2026-08-12 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_challan_challanline'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='challan',
            field=models.ForeignKey(blank=True, help_text="The challan this payment was recorded against, if any - lets a challan's own paid/unpaid status be tracked independently of the fee item's overall balance, since one fee item can now be split across several installment challans.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.challan'),
        ),
    ]
