# Generated by Django 6.0.7 on 2026-08-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_section'),
        ('finance', '0003_payment_challan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_recurring', models.BooleanField(default=True, help_text='Same meaning as FeeStructure.is_recurring.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_overrides', to='finance.feecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_overrides', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['student', 'category'],
                'unique_together': {('student', 'category')},
            },
        ),
    ]
