# Generated by Django 6.0.7 on 2026-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='semester',
            name='unique_current_semester_per_program',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('program',), name='unique_current_semester_per_program', violation_error_message='This program already has a current semester. Edit the existing one to unmark it as current first.'),
        ),
    ]
