# Generated by Django 6.0.7 on 2026-08-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_semester_unique_current_semester_per_program'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semester',
            name='unique_current_semester_per_program',
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Whether this semester is actively running right now. More than one semester of the same program can be current at once - e.g. Semester 3 and Semester 5 both running concurrently for different cohorts of the same program.'),
        ),
    ]
