# Generated by Django 6.0.7 on 2026-08-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_semester_unique_current_semester_per_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sessions_per_week',
            field=models.PositiveSmallIntegerField(default=1, help_text='Timetable slots needed per week for this course.'),
        ),
    ]
