# Generated by Django 6.0.7 on 2026-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_sessions_per_week'),
        ('timetable', '0002_seed_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='joint_offerings',
            field=models.ManyToManyField(blank=True, help_text='Other course offerings that also attend this same physical class (e.g. two programs sharing one lecture) - not a separate booking.', related_name='joint_timetable_entries', to='academics.courseoffering'),
        ),
    ]
