from django.conf import settings
from django.db import models

from apps.attendance.models import LectureSession
from apps.common.models import TimeStampedModel


class DayBookEntry(TimeStampedModel):
    """Wraps a LectureSession with a verification workflow.

    Reuses `LectureSession` as the single source of truth for "a lecture
    happened" instead of duplicating that fact, so attendance and payroll
    counts never disagree.
    """

    session = models.OneToOneField(
        LectureSession, on_delete=models.CASCADE, related_name='daybook_entry'
    )
    verified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='+',
    )
    verified_at = models.DateTimeField(null=True, blank=True)
    remarks = models.TextField(blank=True)

    class Meta:
        ordering = ['-session__date']

    @property
    def is_verified(self):
        return self.verified_by_id is not None

    def __str__(self):
        return f'Day book entry - {self.session}'


class MonthlyWorkloadSnapshot(TimeStampedModel):
    """Auditable payroll export snapshot for one teacher/month, generated by a Coordinator."""

    teacher = models.ForeignKey(
        'accounts.TeacherProfile', on_delete=models.CASCADE, related_name='workload_snapshots'
    )
    year = models.PositiveSmallIntegerField()
    month = models.PositiveSmallIntegerField()
    total_lectures = models.PositiveIntegerField(default=0)
    verified_lectures = models.PositiveIntegerField(default=0)
    per_lecture_rate = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount = models.DecimalField(max_digits=12, decimal_places=2)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='+'
    )

    class Meta:
        ordering = ['-year', '-month', 'teacher']
        unique_together = ('teacher', 'year', 'month')

    def __str__(self):
        return f'{self.teacher} - {self.year}-{self.month:02d}'
